FROM node:23-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . /app

# Start the app
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
