FROM python:3.11-slim

WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

COPY entrypoint_dev.sh /entrypoint_dev.sh
RUN chmod +x /entrypoint_dev.sh
ENTRYPOINT ["/entrypoint_dev.sh"]